import type { Metadata } from "next";
import "./globals.css";
import RootProviders from "@/src/components/provider/RootProviders";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <RootProviders>{children}</RootProviders>
            </body>
        </html>
    );
}
